#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
roll() {
    printf "Enter a number:  "
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=$(cut -b 1-2 <<< ${ALPHA})
    O=$(cut -b 1-2 <<< ${OMEGA})
    let "NUM=$A % $O"
    MONSTER=$RANDOM
    MONSTER=$(cut -b 1-2 <<< ${MONSTER})
    NUM=$(cut -b 1-2 <<< ${NUM})

    echo "The monster rolled " $MONSTER
    echo "You rolled " $NUM
    resolve
}

gameover () {
    cat << EOF > corpse
You see the corpse of a slain adv